apiVersion: v1
kind: Service 
metadata: 
  name: platformnpservice-srv 
spec: 
  type: NodePort
  selector: 
    app: platformservice
  ports: 
    - name: http
      protocol: TCP
      port: 80       # Porta exposta pelo Service
      targetPort: 80  # Porta no container onde a aplicação está escutando 
      